=== pollengun/Web-tech-practical-report-codes/AJAX and XML/q3/class.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com">

    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="id" type="xs:string" />
                            <xs:element name="branch">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="specialization" type="xs:string"
                                            minOccurs="1" maxOccurs="3" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cgpa" type="xs:decimal" />

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== pollengun/Web-tech-practical-report-codes/AJAX and XML/q3/class.xml
<?xml version="1.0" encoding="utf-8"?>
<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.com class.xsd">
    <student>
        <name> Subhash </name>
        <id> 001 </id>
        <branch> CSIT </branch>
        <cgpa> 9.0 </cgpa>
    </student>
    <student>
        <name> Mahesh </name>
        <id> 003 </id>
        <branch> BCA </branch>
        <cgpa> 8.0 </cgpa>
    </student>
    <student>
        <name> Anup </name>
        <id> 008 </id>
        <branch> BBM </branch>
        <cgpa> 7.8 </cgpa>
    </student>
</class>
