=== pollengun/Web-tech-practical-report-codes/AJAX and XML/q2/class.dtd
<!ELEMENT class (student*)>
<!ELEMENT student (name, branch, cgpa)>
<!ATTLIST student id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
<!ELEMENT cgpa (#PCDATA)>

=== pollengun/Web-tech-practical-report-codes/AJAX and XML/q2/Class.XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE class SYSTEM "class.dtd">
<class>
    <student id="001">
        <name> Subhash </name>
        <branch> CSIT </branch>
        <cgpa> 9.0 </cgpa>
    </student>
    <student id="003">
        <name> Mahesh </name>
        <branch> BCA </branch>
        <cgpa> 8.0 </cgpa>
    </student>
    <student id="008">
        <name> Anup </name>
        <branch> BBM </branch>
        <cgpa> 7.8 </cgpa>
    </student>
</class>
